language: python
python:
- '3.8'
env:
  - PYTHONPATH=$TRAVIS_BUILD_DIR
install:
- pip install -r dev-requirements.txt
script:
- cd docs
- make html
deploy:
  provider: pages:git
  token:
    secure: "mcx5IxcfeVRp2wzb1i9BCnnpYPXbbtfXBJf1F+YNcYEgVtaVC08B1AYoPAab0bMZCE2V2ZvKsDin4jE6LOpLtsJB7I4h4KHyVHxLEBaW9QRH/PyQceDlaa3f/L2STFHobdsQEw53psTTmkVAeRnX2aRwMaUXZslZZ78E8M0ja/wOVSa14RaKjk3Oo/aIy0eGjfn8rruB8JhTNRueEBC8KPionGoT+1y64ND94mnq7NCf+0PR7bVBF/eZL7+ywiOYdAN4/T6HBSqNV6OltfRAM1kUWFs3yMIdKxcHXTNE95T1bsMdcULiD66qjBSIppMz6dxKw1dt4mho9gZPLmi07ZMV/8YDcGqgOAdQcnY+H2EnsGlAJ78I4DykrVhWE4hGWtplOyAHkV2FHqshC3LImjyycZ5Dxvp6bd0m3oXT1WZaCoLst9wKC53cELLjVUjcN8xc3jtlb6DlyuczsemdPr+AELpgTHUttzngbROzB/X/yMDsGIucdsE+P4/HKFigd2W+ANRun5ObA5xvaFaOMClj7xLub4dDXxkbx66/dvdB8A1SAicFr0h/ZKSU1/I5upL8jbepvrWRVUpEBd/0QhRezbXWvAuGJ2H5dYm2NPOZg7pVMF6ToQoPQOgw25jRDziWOyEUZxRaDKZagRTGn4u2+sxDvmVxsJ+Xpm/wXq0="
  edge: true
  verbose: true
  local_dir: "./_build/html/"
  keep_history: true
  on:
    branch: main
